import type { ProcessAlert, IntegrityScore, WindowEvent } from '../types';

export function calculateIntegrityScore(
  alerts: ProcessAlert[],
  windowEvents: WindowEvent[],
): IntegrityScore {
  let processDeductions = 0;
  let behaviorDeductions = 0;

  // Process-based deductions
  for (const alert of alerts) {
    switch (alert.threat) {
      case 'critical': processDeductions += 30; break;
      case 'high': processDeductions += 20; break;
      case 'medium': processDeductions += 10; break;
      case 'low': processDeductions += 5; break;
    }
  }

  // Behavior-based deductions (window switching patterns)
  if (windowEvents.length > 0) {
    const shortSwitches = windowEvents.filter((e) => e.duration > 0 && e.duration < 3000);
    const switchRatio = shortSwitches.length / windowEvents.length;
    if (switchRatio > 0.5) behaviorDeductions += 20;
    else if (switchRatio > 0.3) behaviorDeductions += 10;

    // Total switches per minute
    const sessionDuration = windowEvents[windowEvents.length - 1].timestamp - windowEvents[0].timestamp;
    const switchesPerMin = (windowEvents.length / (sessionDuration / 60000)) || 0;
    if (switchesPerMin > 10) behaviorDeductions += 15;
    else if (switchesPerMin > 5) behaviorDeductions += 8;
  }

  const processIntegrity = Math.max(0, 100 - processDeductions);
  const behaviorIntegrity = Math.max(0, 100 - behaviorDeductions);
  const overall = Math.round((processIntegrity * 0.6 + behaviorIntegrity * 0.4));

  let verdict: IntegrityScore['verdict'] = 'clean';
  if (overall < 50) verdict = 'flagged';
  else if (overall < 75) verdict = 'suspicious';

  return { overall, processIntegrity, behaviorIntegrity, verdict };
}

export function generateIntegrityReport(
  candidateName: string,
  role: string,
  alerts: ProcessAlert[],
  windowEvents: WindowEvent[],
  score: IntegrityScore,
): string {
  const timestamp = new Date().toISOString();
  const criticals = alerts.filter((a) => a.threat === 'critical');
  const highs = alerts.filter((a) => a.threat === 'high');

  return [
    `# Interview Integrity Report`,
    ``,
    `| Field | Value |`,
    `|-------|-------|`,
    `| **Candidate** | ${candidateName} |`,
    `| **Role** | ${role} |`,
    `| **Date** | ${new Date().toLocaleDateString()} |`,
    `| **Generated** | ${timestamp} |`,
    ``,
    `## Integrity Score`,
    ``,
    `| Metric | Score |`,
    `|--------|-------|`,
    `| **Overall** | ${score.overall}/100 |`,
    `| **Process Integrity** | ${score.processIntegrity}/100 |`,
    `| **Behavior Integrity** | ${score.behaviorIntegrity}/100 |`,
    `| **Verdict** | ${score.verdict.toUpperCase()} |`,
    ``,
    `## Detected Threats`,
    ``,
    alerts.length === 0
      ? 'No AI tools or suspicious processes detected.'
      : alerts
          .map(
            (a) =>
              `- **[${a.threat.toUpperCase()}]** ${a.name} — ${a.reason} _(${new Date(a.timestamp).toLocaleTimeString()})_`,
          )
          .join('\n'),
    ``,
    `## Window Activity Summary`,
    ``,
    `- Total window switches: ${windowEvents.length}`,
    `- Rapid switches (< 3s): ${windowEvents.filter((e) => e.duration > 0 && e.duration < 3000).length}`,
    ``,
    `## Recommendation`,
    ``,
    criticals.length > 0
      ? `**FLAGGED:** ${criticals.length} critical threat(s) detected. This interview should be reviewed and potentially invalidated.`
      : highs.length > 0
        ? `**SUSPICIOUS:** ${highs.length} high-severity finding(s). Manual review recommended.`
        : `**CLEAN:** No significant integrity concerns detected.`,
    ``,
    `---`,
    `_Generated by Dragon Tracer v0.1.0_`,
  ].join('\n');
}
